name: build-test-deploy
on: push
jobs:
  build-test-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: USE node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm i
      - run: npm run build
